# Generated by Django 3.2.9 on 2021-11-26 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='film',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
    ]
